services:
  server:
    container_name: linksapi_appserver
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=postgres;User Id=postgres;Password=postgres;

  db:
    container_name: postgres_db
    build:
      context: .
      dockerfile: db/Dockerfile
    image: postgres
    restart: always
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db_password:
    file: secrets/db_password.txt

volumes:
  db_data:
