[environments.development]
url = "jdbc:postgresql://db:5432/postgres"
user = "migrations_flyway"                         
password = "development"
schemas = ["public"]
connectRetries = 60

[flyway]
environment = "development"
locations = ["filesystem:./sql"]
