[environments.development]
url = "jdbc:postgresql://db:5432/postgres"
user = "postgres"                          # TODO: Create flyway user to handle migrations
password = "postgres"                      #TODO: Flyway user password
schemas = ["public"]
connectRetries = 60

[flyway]
environment = "development"
locations = ["filesystem:./sql"]
